sudo: false
language: node_js
node_js:
  - node
deploy:
  provider: npm
  email: v.klymenko@douleutaras.com
  api_key:
    secure: Jvvr68R1FFgGtyr9P/Arf36W9iWBGYppzTP+nx4Q2BrM4SwWR1780d2ZYtfn0Fw4EndXQvF+q61diaXSTJJqPTsGOca/o8COa76Jo+nqHpf5jLcDRI3cbp3m59hWgP9DmQdSjumtsMWWEcimNILetkrk8I/Eor9p48he5aMVdwe3d94SC1t4PATWyhbWkqak/zks5nUbUgQmBsfhXjJGua/OeSTXr1pZD5VWHBr0rzDmCvFp+h0DeDLB4qtThuIYuh2UrEtZVSwS1u5mokde7mwEXpgdCE3P4yQHSsjCeaPsGMGMhXZShmtqqQplXSlNmdj21gm14FgYN+S6gIMo5f6LR68dwlkj6x4LJW4wKBurChJVUJOn+Xj3PD6xuTH3UJcQ1b7O7aMVWqTPV0ANiltPzEAPj4C8uL2HBVJrJabnHmw9t0Pp0E1eT5aPT3DpFdsjCYvLP3/7G89VPYMdFkO5JjJQFtzmkGixjBYGFJdXXdbfIRuae3iilfpgrz67e4GPOBdqqiP+SFBq/ixheb6fgc1tTZBztrOydqcRBdJd63/nM4UtpRy13ngU0wXfm1a1DkSvjSEOokDKKl8JecC4BRrhPFflWWolWLgJe1I0y5ZbIc2+254Um64NK5P64XrNZLSlFOXgJg+ZGX03VuPnIRHgQ5k0IkIlx1Ge+es=
  on:
    repo: douleutaras/gulp-angular-gettext
